development:
  adapter: postgresql
  encoding: utf8
  database: i_no_this_dev
  username: i_no
  password: pass
  host: localhost

test:
  adapter: postgresql
  encoding: utf8
  database: i_no_this_test
  username: i_no
  password: pass
  host: localhost

production:
  adapter: postgresql
  encoding: utf8
  database: i_no_this_prod
  username: i_no
  password: pass
  host: localhost
